// Generated by CoffeeScript 1.10.0
(function() {
  var environment, getUserHome, launcher;

  launcher = require('browser-launcher2');

  environment = require('./environment.js');

  exports.launchme = function(env, testbrowser, cb) {
    debugger;
    launcher(getUserHome() + "\\.config\\browser-launcher2\\config.json", function(err, launch) {
      debugger;
      if (err) {
        throw err;
      }
      debugger;
      environment.url(env, function(url) {
        var options, uri;
        uri = url;
        options = {
          browser: testbrowser
        };
        launch(uri, options, function(err, instance) {
          if (err) {
            throw err;
          }
          cb(instance);
        });
      });
    });
  };

  getUserHome = function() {
    return process.env[process.platform === 'win32' ? 'USERPROFILE' : 'HOME'];
  };

}).call(this);
