// Generated by CoffeeScript 1.10.0
(function() {
  var EventEmitter, exec, readline, stream, tedriver,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  exec = require('child_process').exec;

  readline = require('readline');

  stream = require('stream');

  EventEmitter = require('events');

  module.exports = tedriver = (function(superClass) {
    extend(tedriver, superClass);

    function tedriver(paramObj) {
      tedriver.__super__.constructor.call(this, paramObj, 'TestExecute');
    }

    return tedriver;

  })(EventEmitter);

}).call(this);
