// Generated by CoffeeScript 1.10.0
(function() {
  var TestToolFactory, tc, te;

  tc = require('./tcdriver.js');

  te = require('./tedriver.js');

  module.exports = TestToolFactory = (function() {
    function TestToolFactory() {}

    TestToolFactory.prototype.createObject = function(paramObj) {
      switch (process.env.oletesttool) {
        case 'TestComplete':
          return new tc(paramObj);
        case 'TestExecute':
          return new te(paramObj);
        default:
          throw new TypeError('Invalid/Unsupported Testing tool. Fix: set oletesttool=TestComplete');
      }
    };

    return TestToolFactory;

  })();

}).call(this);
